learningtemplates/basicapp/urls.py
from django.urls import path
#from django.conf.urls import url
from basicapp import views

#TEMPLATE TAGGING
app_name = 'basicapp'

urlpatterns = [
    #url(r'^relative/$',views.relative,name='relative'),
    path('relative/',views.relative, name='relative'),
    #url(r'^other/$',views.other,name='other')
    path('other/',views.other, name='other'),
]

learningtemplates/learningtemplates/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/',admin.site.urls),
    path('basicapp/',include('basicapp.urls'))

]

learningtemplates/basicapp/models.py
from django.db import models

# Create your models here.

learningtemplates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relativeurltemplates.html')

learningtemplates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>
  </body>
</html>

learningtemplates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
    {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <!-- <h1>This is index.html page showing!</h1> -->
    <h1>{{ text|cut:'world'}}</h1>
    <h1>{{ number|add:"99" }}</h1>
    {% endblock %}

learningtemplates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html"%}
{% block body_block %}
  <h1>WELCOME TO OTHER!</h1>
  <h2>This is an example of template inheritance!</h2>
{% endblock %}

learningtemplates/templates/basicapp/relativeurltemplates.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title></title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX!</a>
</body>
</html>